// AUTO-GENERATED — do not edit by hand.
// Source: Hydrawave3/packages/placement-core/src/knowledge/anatomyCalibration.js
// Regenerate: node extract-anatomy-calibration.mjs
//
// 39 calibrated landmarks shared with the web AnatomyScene. The GLB and its
// normalization (BODY_TARGET_HEIGHT 4.22 / BODY_TARGET_CENTER_Y 0.24) are
// identical on both sides, so these coordinates transfer without adjustment.

export const ANATOMY_LANDMARK_MAP_VERSION = "shared-anatomy-calibration-v1";

export const ANATOMY_LANDMARKS = [
  {
    key: "thoracolumbar",
    zone: "thoracolumbar",
    region: "Thoracolumbar junction",
    view: "back",
    absX: 0.07,
    y: 1.27,
    z: -0.43,
    normalX: 0.08,
    normalY: 0,
    normalZ: -1,
    matcher: /thoracolumbar|t12|l1|lower rib|upper lumbar/i,
    cue: "Thoracolumbar junction just beside the spine at the lower-rib / upper-waist line",
  },
  {
    key: "low_back_l23",
    zone: "low_back_l23",
    region: "L2-L3 lumbar paraspinal",
    view: "back",
    absX: 0.12,
    y: 1.18,
    z: -0.42,
    normalX: 0.16,
    normalY: 0,
    normalZ: -0.99,
    matcher: /l2|l3|low back|lumbar|posterior.*spine|right of spine|left of spine/i,
    cue: "Lumbar paraspinal column beside the L2-L3 level",
  },
  {
    key: "iliac_fossa",
    zone: "iliac_fossa",
    region: "Anterior iliac fossa",
    view: "front",
    absX: 0.21,
    y: 0.78,
    z: 0.34,
    normalX: 0.26,
    normalY: 0,
    normalZ: 0.97,
    matcher: /iliac fossa|iliacus|psoas|iliopsoas|hip flexor|front hip|anterior iliac|inner iliac/i,
    cue: "Front inner hip pocket over the iliopsoas / iliacus line",
  },
  {
    key: "external_oblique",
    zone: "external_oblique",
    region: "External oblique",
    view: "front",
    absX: 0.31,
    y: 1.09,
    z: 0.28,
    normalX: 0.58,
    normalY: 0,
    normalZ: 0.82,
    matcher: /external oblique|oblique|anterolateral abdomen|front side core|abdom/i,
    cue: "Anterolateral abdomen between the lower ribs and iliac crest",
  },
  {
    key: "lat",
    zone: "lat",
    region: "Latissimus dorsi",
    view: "side",
    absX: 0.39,
    y: 1.4,
    z: -0.24,
    normalX: 0.72,
    normalY: 0,
    normalZ: -0.7,
    matcher: /latissimus|\blat\b|thoracolumbar fascia|inferolateral lat|low-back tissue sheet/i,
    cue: "Inferolateral lat and thoracolumbar fascia line",
  },
  {
    key: "hamstring_origin",
    zone: "hamstring_origin",
    region: "Proximal hamstring origin",
    view: "back",
    absX: 0.23,
    y: 0.43,
    z: -0.35,
    normalX: 0.34,
    normalY: -0.03,
    normalZ: -0.94,
    matcher: /hamstring origin|ischial|sit bone|semitendinosus|biceps femoris|proximal hamstring/i,
    cue: "Upper hamstring origin directly under the sit-bone line",
  },
  {
    key: "medial_hamstring_origin",
    zone: "medial_hamstring_origin",
    region: "Medial proximal hamstring origin",
    view: "back",
    absX: 0.17,
    y: 0.43,
    z: -0.34,
    normalX: 0.22,
    normalY: -0.03,
    normalZ: -0.98,
    matcher: /medial proximal hamstring|medial hamstring|semitendinosus|semimembranosus/i,
    cue: "Medial upper hamstring origin just below the sit-bone line",
  },
  {
    key: "lateral_ischial_tuberosity",
    zone: "lateral_ischial_tuberosity",
    region: "Lateral ischial tuberosity",
    view: "back",
    absX: 0.29,
    y: 0.44,
    z: -0.34,
    normalX: 0.48,
    normalY: -0.02,
    normalZ: -0.88,
    matcher: /lateral ischial|ischial tuberosity|lateral sit bone|biceps femoris/i,
    cue: "Lateral sit-bone / outer proximal hamstring line",
  },
  {
    key: "posterior_hip",
    zone: "posterior_hip",
    region: "Posterior hip / piriformis",
    view: "back",
    absX: 0.29,
    y: 0.7,
    z: -0.39,
    normalX: 0.5,
    normalY: 0,
    normalZ: -0.87,
    matcher: /piriformis|posterior hip|external rotator|glute medius/i,
    cue: "Posterior hip pocket between sacrum and outer hip",
  },
  {
    key: "posterior_ilium",
    zone: "posterior_ilium",
    region: "Posterior ilium / posterior hip crest",
    view: "back",
    absX: 0.22,
    y: 0.76,
    z: -0.38,
    normalX: 0.36,
    normalY: 0,
    normalZ: -0.93,
    matcher: /posterior ilium|ilium.*posterior hip|posterior iliac|iliac crest/i,
    cue: "Posterior ilium just below the back hip crest",
  },
  {
    key: "piriformis_posterior_hip",
    zone: "piriformis_posterior_hip",
    region: "Piriformis / posterior hip external rotators",
    view: "back",
    absX: 0.29,
    y: 0.69,
    z: -0.39,
    normalX: 0.5,
    normalY: 0,
    normalZ: -0.87,
    matcher: /piriformis|external rotator|deep back hip/i,
    cue: "Deep posterior hip pocket over the piriformis / external rotator line",
  },
  {
    key: "gluteus_medius_posterior_hip",
    zone: "gluteus_medius_posterior_hip",
    region: "Gluteus medius posterior hip",
    view: "back",
    absX: 0.34,
    y: 0.78,
    z: -0.3,
    normalX: 0.58,
    normalY: 0,
    normalZ: -0.82,
    matcher: /gluteus medius|glute medius|posterior glute medius/i,
    cue: "High outer posterior hip over the gluteus medius line",
  },
  {
    key: "gluteus_maximus_upper_belly",
    zone: "gluteus_maximus_upper_belly",
    region: "Gluteus maximus upper belly",
    view: "back",
    absX: 0.26,
    y: 0.56,
    z: -0.36,
    normalX: 0.52,
    normalY: 0,
    normalZ: -0.86,
    matcher: /gluteus maximus.*upper|upper glute belly|glute max.*belly/i,
    cue: "Outer upper glute max muscle belly",
  },
  {
    key: "gluteus_maximus_tuberosity",
    zone: "gluteus_maximus_tuberosity",
    region: "Gluteus maximus at gluteal tuberosity",
    view: "back",
    absX: 0.16,
    y: 0.48,
    z: -0.42,
    normalX: 0.22,
    normalY: 0,
    normalZ: -0.98,
    matcher: /gluteal tuberosity|gluteus maximus.*distal|glute max insertion|posterior glute max insertion/i,
    cue: "Lower glute max insertion near the gluteal fold",
  },
  {
    key: "pectoralis_minor_coracoid",
    zone: "pectoralis_minor_coracoid",
    region: "Pectoralis minor at coracoid",
    view: "front",
    absX: 0.38,
    y: 1.61,
    z: 0.24,
    normalX: 0.48,
    normalY: 0.02,
    normalZ: 0.88,
    matcher: /pectoralis minor|pectoralis|pec.*minor|\bpec\b|front shoulder|coracoid/i,
    cue: "Front shoulder / upper pec at the coracoid process",
  },
  {
    key: "infraspinatus_greater_tubercle",
    zone: "infraspinatus_greater_tubercle",
    region: "Infraspinatus to greater tubercle",
    view: "back",
    absX: 0.38,
    y: 1.57,
    z: -0.34,
    normalX: 0.44,
    normalY: 0,
    normalZ: -0.9,
    matcher: /infraspinatus|greater tubercle/i,
    cue: "Posterior rotator cuff near the greater tubercle line",
  },
  {
    key: "anterior_deltoid",
    zone: "anterior_deltoid",
    region: "Anterior deltoid",
    view: "front",
    absX: 0.53,
    y: 1.72,
    z: 0.13,
    normalX: 0.74,
    normalY: 0.04,
    normalZ: 0.67,
    matcher: /anterior deltoid|front shoulder|shoulder flexion|pec/i,
    cue: "Front shoulder cap",
  },
  {
    key: "posterior_deltoid",
    zone: "posterior_deltoid",
    region: "Posterior deltoid",
    view: "back",
    absX: 0.5,
    y: 1.68,
    z: -0.22,
    normalX: 0.64,
    normalY: 0.03,
    normalZ: -0.77,
    matcher: /posterior deltoid|rear shoulder|back shoulder/i,
    cue: "Back shoulder cap",
  },
  {
    key: "serratus_anterior_rib7",
    zone: "serratus_anterior_rib7",
    region: "Serratus anterior at rib 7",
    view: "side",
    absX: 0.48,
    y: 1.45,
    z: 0.03,
    normalX: 0.94,
    normalY: 0,
    normalZ: 0.34,
    matcher: /serratus anterior|rib 7|lateral ribcage/i,
    cue: "Side ribcage under the shoulder blade around rib 7",
  },
  {
    key: "serratus_posterior_inferior_t11_t12",
    zone: "serratus_posterior_inferior_t11_t12",
    region: "Serratus posterior inferior at T11-T12",
    view: "back",
    absX: 0.18,
    y: 1.29,
    z: -0.41,
    normalX: 0.18,
    normalY: 0,
    normalZ: -0.98,
    matcher: /serratus posterior inferior|lower thoracic|t11|t12/i,
    cue: "Lower thoracic back around T11-T12",
  },
  {
    key: "splenius_capitis_c2_c3",
    zone: "splenius_capitis_c2_c3",
    region: "Splenius capitis at C2-C3",
    view: "back",
    absX: 0.1,
    y: 2.04,
    z: -0.23,
    normalX: 0.16,
    normalY: -0.03,
    normalZ: -0.99,
    matcher: /splenius capitis|posterior neck.*c2|c2.?c3/i,
    cue: "Posterior upper neck around C2-C3",
  },
  {
    key: "levator",
    zone: "levator",
    region: "Levator scapulae",
    view: "back",
    absX: 0.22,
    y: 1.83,
    z: -0.26,
    normalX: 0.42,
    normalY: 0,
    normalZ: -0.91,
    matcher: /levator|superior medial scapular|upper medial scapula|neck.*shoulder/i,
    cue: "Upper medial scapular border where levator scapulae attaches",
  },
  {
    key: "rhomboid",
    zone: "rhomboid",
    region: "Rhomboid / medial scapular border",
    view: "back",
    absX: 0.19,
    y: 1.58,
    z: -0.4,
    normalX: 0.24,
    normalY: 0,
    normalZ: -0.97,
    matcher: /rhomboid|between spine and shoulder blade|medial scapula/i,
    cue: "Medial scapular border between spine and shoulder blade",
  },
  {
    key: "pronator_teres_medial_epicondyle",
    zone: "pronator_teres_medial_epicondyle",
    region: "Pronator teres at medial epicondyle",
    view: "side",
    absX: 0.83,
    y: 1.32,
    z: 0.08,
    normalX: -0.58,
    normalY: 0,
    normalZ: 0.82,
    matcher: /medial epicondyle|flexor.pronator/i,
    cue: "Inside-front elbow at the flexor-pronator origin / medial epicondyle",
  },
  {
    key: "triceps_olecranon",
    zone: "triceps_olecranon",
    region: "Triceps insertion at olecranon",
    view: "side",
    absX: 0.83,
    y: 1.27,
    z: -0.08,
    normalX: -0.2,
    normalY: 0,
    normalZ: -0.98,
    matcher: /triceps|olecranon/i,
    cue: "Back elbow point at triceps / olecranon",
  },
  {
    key: "extensor_carpi_ulnaris_forearm",
    zone: "extensor_carpi_ulnaris_forearm",
    region: "Extensor carpi ulnaris forearm",
    view: "side",
    absX: 1.04,
    y: 0.94,
    z: -0.1,
    normalX: 0.36,
    normalY: 0,
    normalZ: -0.93,
    matcher: /extensor carpi ulnaris|posterior forearm|extensor forearm/i,
    cue: "Posterior lower forearm extensor line",
  },
  {
    key: "anterior_distal_forearm",
    zone: "anterior_distal_forearm",
    region: "Anterior distal forearm",
    view: "side",
    absX: 1.06,
    y: 0.92,
    z: 0.12,
    normalX: 0.45,
    normalY: 0,
    normalZ: 0.89,
    matcher: /anterior distal forearm|palmar|palm-side|flexor forearm|mid forearm|medial forearm/i,
    cue: "Palm-side lower forearm on the flexor/pronator line",
  },
  {
    key: "posterior_distal_forearm",
    zone: "posterior_distal_forearm",
    region: "Posterior distal forearm",
    view: "side",
    absX: 1.04,
    y: 0.94,
    z: -0.1,
    normalX: 0.36,
    normalY: 0,
    normalZ: -0.93,
    matcher: /posterior distal forearm|posterior forearm|extensor|supinator|dorsal forearm/i,
    cue: "Back-side lower forearm on the extensor/supinator line",
  },
  {
    key: "sartorius_pes_anserine",
    zone: "sartorius_pes_anserine",
    region: "Sartorius / pes anserine medial knee",
    view: "front",
    absX: 0.13,
    y: -0.64,
    z: 0.12,
    normalX: -0.68,
    normalY: 0,
    normalZ: 0.73,
    matcher: /sartorius|pes anserine|proximal medial tibia|above medial knee/i,
    cue: "Medial proximal tibia / pes anserine just below the knee",
  },
  {
    key: "rectus_femoris_quad_tendon",
    zone: "rectus_femoris_quad_tendon",
    region: "Rectus femoris / quad tendon above patella",
    view: "front",
    absX: 0.23,
    y: -0.46,
    z: 0.24,
    normalX: 0,
    normalY: 0,
    normalZ: 1,
    matcher: /rectus femoris|quad tendon|above patella/i,
    cue: "Quadriceps tendon directly above the kneecap",
  },
  {
    key: "vastus_medialis_vmo",
    zone: "vastus_medialis_vmo",
    region: "Vastus medialis above medial patella",
    view: "front",
    absX: 0.17,
    y: -0.38,
    z: 0.19,
    normalX: -0.35,
    normalY: 0,
    normalZ: 0.94,
    matcher: /vastus medialis|vmo|above medial patella/i,
    cue: "VMO / inside quad above the kneecap",
  },
  {
    key: "vastus_lateralis_vl",
    zone: "vastus_lateralis_vl",
    region: "Vastus lateralis above lateral patella",
    view: "front",
    absX: 0.29,
    y: -0.36,
    z: 0.17,
    normalX: 0.56,
    normalY: 0,
    normalZ: 0.83,
    matcher: /vastus lateralis.*above|vl|above lateral patella|anterior hip joint/i,
    cue: "Outside quad above the kneecap / proximal vastus lateralis line",
  },
  {
    key: "popliteus_posterior_knee",
    zone: "popliteus_posterior_knee",
    region: "Popliteus posterior knee",
    view: "back",
    absX: 0.22,
    y: -0.5,
    z: -0.23,
    normalX: 0.18,
    normalY: 0,
    normalZ: -0.98,
    matcher: /popliteus|posterior knee/i,
    cue: "Back of knee above the crease; avoid the center of the fossa",
  },
  {
    key: "tibialis_anterior_tuberosity",
    zone: "tibialis_anterior_tuberosity",
    region: "Tibialis anterior at tibial tuberosity",
    view: "front",
    absX: 0.2,
    y: -0.66,
    z: 0.18,
    normalX: -0.22,
    normalY: 0,
    normalZ: 0.98,
    matcher: /tibialis anterior.*tibial tuberosity|tibial tuberosity/i,
    cue: "Front upper shin at the tibial tuberosity / tibialis anterior origin",
  },
  {
    key: "fibularis_longus_fibular_head",
    zone: "fibularis_longus_fibular_head",
    region: "Fibularis longus at fibular head",
    view: "front",
    absX: 0.33,
    y: -0.58,
    z: 0.06,
    normalX: 0.85,
    normalY: 0,
    normalZ: 0.52,
    matcher: /fibularis longus.*fibular head|peroneal.*fibular head|fibular head/i,
    cue: "Outside upper shin at fibular head / fibularis longus origin",
  },
  {
    key: "tibialis_posterior_medial_malleolus",
    zone: "tibialis_posterior_medial_malleolus",
    region: "Tibialis posterior above medial malleolus",
    view: "front",
    absX: 0.13,
    y: -1.57,
    z: 0.03,
    normalX: -0.88,
    normalY: 0,
    normalZ: 0.48,
    matcher: /tibialis posterior|above medial malleolus|posterior tibialis/i,
    cue: "Inside ankle just above the medial malleolus",
  },
  {
    key: "fibularis_longus_lateral_malleolus",
    zone: "fibularis_longus_lateral_malleolus",
    region: "Fibularis longus above lateral malleolus",
    view: "front",
    absX: 0.34,
    y: -1.56,
    z: 0.03,
    normalX: 0.88,
    normalY: 0,
    normalZ: 0.48,
    matcher: /fibularis longus.*lateral malleolus|above lateral malleolus|peroneal/i,
    cue: "Outside ankle just above the lateral malleolus",
  },
  {
    key: "tibialis_anterior_medial_cuneiform",
    zone: "tibialis_anterior_medial_cuneiform",
    region: "Tibialis anterior insertion at medial cuneiform",
    view: "side",
    absX: 0.23,
    y: -1.78,
    z: 0.19,
    normalX: 0,
    normalY: 0.22,
    normalZ: 0.98,
    matcher: /tibialis anterior.*medial cuneiform|medial cuneiform/i,
    cue: "Top/medial midfoot at tibialis anterior insertion",
  },
  {
    key: "flexor_digitorum_brevis_arch",
    zone: "flexor_digitorum_brevis_arch",
    region: "Flexor digitorum brevis at central plantar arch",
    view: "side",
    absX: 0.23,
    y: -1.84,
    z: -0.05,
    normalX: 0,
    normalY: -0.46,
    normalZ: -0.89,
    matcher: /flexor digitorum brevis|central plantar arch|plantar arch/i,
    cue: "Central plantar arch under the foot",
  },
];
